# https://supabase.com/docs/guides/functions/function-configuration
[functions.contact-submit]
verify_jwt = false

[functions.application-notify]
verify_jwt = false

[functions.event-register-notify]
verify_jwt = true
