/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OverOnsRouteImport } from './routes/over-ons'
import { Route as MissieVisieRouteImport } from './routes/missie-visie'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LidmaatschapRouteImport } from './routes/lidmaatschap'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AanmeldenRouteImport } from './routes/aanmelden'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortaalIndexRouteImport } from './routes/portaal.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PortaalProfielRouteImport } from './routes/portaal.profiel'
import { Route as PortaalLedenRouteImport } from './routes/portaal.leden'
import { Route as PortaalAgendaRouteImport } from './routes/portaal.agenda'
import { Route as AdminEventsRouteImport } from './routes/admin.events'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OverOnsRoute = OverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => rootRouteImport,
} as any)
const MissieVisieRoute = MissieVisieRouteImport.update({
  id: '/missie-visie',
  path: '/missie-visie',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LidmaatschapRoute = LidmaatschapRouteImport.update({
  id: '/lidmaatschap',
  path: '/lidmaatschap',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AanmeldenRoute = AanmeldenRouteImport.update({
  id: '/aanmelden',
  path: '/aanmelden',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortaalIndexRoute = PortaalIndexRouteImport.update({
  id: '/portaal/',
  path: '/portaal/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortaalProfielRoute = PortaalProfielRouteImport.update({
  id: '/portaal/profiel',
  path: '/portaal/profiel',
  getParentRoute: () => rootRouteImport,
} as any)
const PortaalLedenRoute = PortaalLedenRouteImport.update({
  id: '/portaal/leden',
  path: '/portaal/leden',
  getParentRoute: () => rootRouteImport,
} as any)
const PortaalAgendaRoute = PortaalAgendaRouteImport.update({
  id: '/portaal/agenda',
  path: '/portaal/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aanmelden': typeof AanmeldenRoute
  '/contact': typeof ContactRoute
  '/lidmaatschap': typeof LidmaatschapRoute
  '/login': typeof LoginRoute
  '/missie-visie': typeof MissieVisieRoute
  '/over-ons': typeof OverOnsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/events': typeof AdminEventsRoute
  '/portaal/agenda': typeof PortaalAgendaRoute
  '/portaal/leden': typeof PortaalLedenRoute
  '/portaal/profiel': typeof PortaalProfielRoute
  '/admin/': typeof AdminIndexRoute
  '/portaal/': typeof PortaalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aanmelden': typeof AanmeldenRoute
  '/contact': typeof ContactRoute
  '/lidmaatschap': typeof LidmaatschapRoute
  '/login': typeof LoginRoute
  '/missie-visie': typeof MissieVisieRoute
  '/over-ons': typeof OverOnsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/events': typeof AdminEventsRoute
  '/portaal/agenda': typeof PortaalAgendaRoute
  '/portaal/leden': typeof PortaalLedenRoute
  '/portaal/profiel': typeof PortaalProfielRoute
  '/admin': typeof AdminIndexRoute
  '/portaal': typeof PortaalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aanmelden': typeof AanmeldenRoute
  '/contact': typeof ContactRoute
  '/lidmaatschap': typeof LidmaatschapRoute
  '/login': typeof LoginRoute
  '/missie-visie': typeof MissieVisieRoute
  '/over-ons': typeof OverOnsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/events': typeof AdminEventsRoute
  '/portaal/agenda': typeof PortaalAgendaRoute
  '/portaal/leden': typeof PortaalLedenRoute
  '/portaal/profiel': typeof PortaalProfielRoute
  '/admin/': typeof AdminIndexRoute
  '/portaal/': typeof PortaalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aanmelden'
    | '/contact'
    | '/lidmaatschap'
    | '/login'
    | '/missie-visie'
    | '/over-ons'
    | '/privacy'
    | '/reset-password'
    | '/admin/events'
    | '/portaal/agenda'
    | '/portaal/leden'
    | '/portaal/profiel'
    | '/admin/'
    | '/portaal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aanmelden'
    | '/contact'
    | '/lidmaatschap'
    | '/login'
    | '/missie-visie'
    | '/over-ons'
    | '/privacy'
    | '/reset-password'
    | '/admin/events'
    | '/portaal/agenda'
    | '/portaal/leden'
    | '/portaal/profiel'
    | '/admin'
    | '/portaal'
  id:
    | '__root__'
    | '/'
    | '/aanmelden'
    | '/contact'
    | '/lidmaatschap'
    | '/login'
    | '/missie-visie'
    | '/over-ons'
    | '/privacy'
    | '/reset-password'
    | '/admin/events'
    | '/portaal/agenda'
    | '/portaal/leden'
    | '/portaal/profiel'
    | '/admin/'
    | '/portaal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AanmeldenRoute: typeof AanmeldenRoute
  ContactRoute: typeof ContactRoute
  LidmaatschapRoute: typeof LidmaatschapRoute
  LoginRoute: typeof LoginRoute
  MissieVisieRoute: typeof MissieVisieRoute
  OverOnsRoute: typeof OverOnsRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminEventsRoute: typeof AdminEventsRoute
  PortaalAgendaRoute: typeof PortaalAgendaRoute
  PortaalLedenRoute: typeof PortaalLedenRoute
  PortaalProfielRoute: typeof PortaalProfielRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PortaalIndexRoute: typeof PortaalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons': {
      id: '/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof OverOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missie-visie': {
      id: '/missie-visie'
      path: '/missie-visie'
      fullPath: '/missie-visie'
      preLoaderRoute: typeof MissieVisieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lidmaatschap': {
      id: '/lidmaatschap'
      path: '/lidmaatschap'
      fullPath: '/lidmaatschap'
      preLoaderRoute: typeof LidmaatschapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aanmelden': {
      id: '/aanmelden'
      path: '/aanmelden'
      fullPath: '/aanmelden'
      preLoaderRoute: typeof AanmeldenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portaal/': {
      id: '/portaal/'
      path: '/portaal'
      fullPath: '/portaal/'
      preLoaderRoute: typeof PortaalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portaal/profiel': {
      id: '/portaal/profiel'
      path: '/portaal/profiel'
      fullPath: '/portaal/profiel'
      preLoaderRoute: typeof PortaalProfielRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portaal/leden': {
      id: '/portaal/leden'
      path: '/portaal/leden'
      fullPath: '/portaal/leden'
      preLoaderRoute: typeof PortaalLedenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portaal/agenda': {
      id: '/portaal/agenda'
      path: '/portaal/agenda'
      fullPath: '/portaal/agenda'
      preLoaderRoute: typeof PortaalAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AanmeldenRoute: AanmeldenRoute,
  ContactRoute: ContactRoute,
  LidmaatschapRoute: LidmaatschapRoute,
  LoginRoute: LoginRoute,
  MissieVisieRoute: MissieVisieRoute,
  OverOnsRoute: OverOnsRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminEventsRoute: AdminEventsRoute,
  PortaalAgendaRoute: PortaalAgendaRoute,
  PortaalLedenRoute: PortaalLedenRoute,
  PortaalProfielRoute: PortaalProfielRoute,
  AdminIndexRoute: AdminIndexRoute,
  PortaalIndexRoute: PortaalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
